version: '2'
services:
  bind:
    image: sameersbn/bind:9.9.5-20161106
    restart: always
    container_name: bind9
    hostname: bind9
    mem_limit: 100M
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    extra_hosts:
      - <Adding here>
    dns:
      - <Adding/Modify here>
    volumes:
      - <Adding/Modify here>
